version: "3.9"
services:
  coupon-management-service:
    environment:
      DB_HOST: coupons-db
      DB_PORT: 3306
      DB_NAME: coupon_management
      DB_USERNAME: root
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
    image: coupon-management-service
    ports:
      - "8080:8080"
    depends_on:
      - gateway
      - rabbitmq
      - coupons-db
    networks:
      - coupon-network

  coupons-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon_management
      MYSQL_USER: coupon_user
      MYSQL_PASSWORD: coupon_password
    volumes:
      - coupons-db:/var/lib/mysql
    ports:
      - '33066:3306'
    networks:
      - coupon-network

  auth-service:
    environment:
      DB_HOST: auth-db
      DB_PORT: 3306
      DB_NAME: auth
      DB_USERNAME: root
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
    image: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - gateway
      - rabbitmq
      - auth-db
    networks:
      - coupon-network

  auth-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
      MYSQL_USER: coupon_user
      MYSQL_PASSWORD: coupon_password
    volumes:
      - auth-db:/var/lib/mysql
    ports:
      - '33067:3306'
    networks:
      - coupon-network

  expired-service:
    image: expired-coupons-service
    restart: always
    environment:
      DB_HOST: expired-db
      DB_PORT: 3306
      DB_NAME: expired_coupons
      DB_USERNAME: root
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
      - expired-db
    networks:
      - coupon-network
  expired-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expired_coupons
      MYSQL_USER: coupon_user
      MYSQL_PASSWORD: coupon_password
    volumes:
      - expired-db:/var/lib/mysql
    ports:
      - '33068:3306'
    networks:
      - coupon-network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - coupon-network
  gateway:
    image: coupons-gateway
    ports:
      - "8085:8085"
    networks:
      - coupon-network
    environment:
      COUPONS_MANAGEMENT_URL: http://coupon-management-service:8080
      AUTH_SERVICE_URL: http://auth-service:8081
networks:
  coupon-network:
    driver: bridge
volumes:
  coupons-db:
  auth-db:
  expired-db: